# Data Source Properties
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:plan;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driverClassName: org.h2.Driver

# ORM Properties
  jpa:
    hibernate:
      ddl-auto: update
