# Data Source Properties
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:plan;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driverClassName: org.h2.Driver

# ORM Properties
  jpa:
    hibernate:
      ddl-auto: update


plan-api:
  constants:
    dataSaveSuccess: Data saved successfully
    dataSaveFailure: Error while saving data please try again

    dataUpdateSuccess: Data updated successfully
    dataUpdateFailure: Error while updating data please try again

    dataDeleteSuccess: Data deleted successfully
    dataDeleteFailure: Error while deleting data please try again

    statusChangeSuccess: Status changed successfully
    statusChangeFailure: Error while changing status please try again



